Full Name: MohammadDavood VahhabRajaee

Student ID: 4041419041

# Introduction to PyTorch

**Goal:**  
Understand what PyTorch is, how to create and manipulate **tensors**, and perform simple mathematical operations.  

## What is PyTorch?

[PyTorch](https://pytorch.org/) is a powerful open-source **deep learning framework** developed by Facebook (Meta).  
It is popular because it’s:
- **Pythonic** — works naturally with Python syntax  
- **Dynamic** — computations run immediately (no static graphs)  
- **Flexible** — allows tensor operations, GPU acceleration, and building complex neural networks easily  

In PyTorch, the **core data structure** is the **Tensor**, which is very similar to a NumPy array but optimized for deep learning.


## Importing PyTorch and checking the version

In [1]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.5.1+cu121


## What is a Tensor?

A **Tensor** is a multi-dimensional array — similar to a NumPy array — that can:
- Store numbers of different types (`float`, `int`, `bool`, etc.)
- Move between CPU and GPU easily
- Support fast mathematical operations

Tensors are the foundation of PyTorch computations.

## Creating Tensors

There are several common ways to create tensors:

In [2]:
# From a Python list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("Tensor from list:\n", x_data)

# From a NumPy array
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("\nTensor from NumPy array:\n", x_np)

# Using built-in functions
x_ones = torch.ones((2, 3))    # All ones
x_zeros = torch.zeros((2, 3))  # All zeros
x_rand = torch.rand((2, 3))    # Random values between 0 and 1
x_full = torch.full((2, 3), 5) # All filled with 5
print("\nOnes:\n", x_ones)
print("\nZeros:\n", x_zeros)
print("\nRandom:\n", x_rand)
print("\nFull of 5s:\n", x_full)

Tensor from list:
 tensor([[1, 2],
        [3, 4]])

Tensor from NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Random:
 tensor([[0.3519, 0.6148, 0.6778],
        [0.1049, 0.8872, 0.6161]])

Full of 5s:
 tensor([[5, 5, 5],
        [5, 5, 5]])


### Explanation:
- `torch.tensor(data)` → creates a tensor directly from Python data.  
- `torch.from_numpy()` → shares memory with the NumPy array (changes in one reflect in the other).  
- `torch.ones`, `torch.zeros`, `torch.rand`, and `torch.full` are convenient initialization functions.


## Tensor Shapes and Dtypes

In [3]:
# Example tensor
x = torch.rand((3, 4))

print("Tensor:\n", x)
print("\nShape:", x.shape)
print("Number of elements:", x.numel())
print("Data type:", x.dtype)
print("Device:", x.device)

Tensor:
 tensor([[0.8298, 0.6742, 0.6782, 0.1433],
        [0.4179, 0.0032, 0.3327, 0.2729],
        [0.7361, 0.7389, 0.7779, 0.2482]])

Shape: torch.Size([3, 4])
Number of elements: 12
Data type: torch.float32
Device: cpu


### Explanation:
- `.shape` → the dimensions of the tensor  
- `.numel()` → total number of elements  
- `.dtype` → data type (e.g., float32, int64)  
- `.device` → tells whether the tensor is stored on **CPU** or **GPU**

## Moving Tensors to GPU (if available)

PyTorch allows you to use GPUs seamlessly.  
Let’s check if CUDA (GPU support) is available.

In [2]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

x_cpu = torch.ones((2, 2))
x_gpu = x_cpu.to(device)

print("Device used:", device)
print("Tensor on CPU:", x_cpu)
print("Tensor moved to:", x_gpu.device)

Device used: cuda
Tensor on CPU: tensor([[1., 1.],
        [1., 1.]])
Tensor moved to: cuda:0


### Explanation:
- `torch.cuda.is_available()` checks if a GPU is accessible.  
- `.to(device)` moves a tensor between CPU and GPU.  
- Tensor operations automatically run on the device where the tensor lives.

## Basic Tensor Operations

In [3]:
# Create two tensors
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Element-wise operations
print("Addition:\n", a + b)
print("\nSubtraction:\n", a - b)
print("\nMultiplication (element-wise):\n", a * b)
print("\nDivision:\n", a / b)

# Matrix multiplication
print("\nMatrix multiplication (dot product):\n", torch.matmul(a, b))
# or equivalently
print("\nUsing @ operator:\n", a @ b)

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])

Subtraction:
 tensor([[-4., -4.],
        [-4., -4.]])

Multiplication (element-wise):
 tensor([[ 5., 12.],
        [21., 32.]])

Division:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Matrix multiplication (dot product):
 tensor([[19., 22.],
        [43., 50.]])

Using @ operator:
 tensor([[19., 22.],
        [43., 50.]])


### Explanation:
- Arithmetic operators (`+`, `-`, `*`, `/`) are element-wise.  
- `torch.matmul()` or `@` performs **matrix multiplication** (dot product).  
- These operations return *new tensors* — the originals stay unchanged.

## Tensor Indexing & Slicing

In [4]:
# Create sample tensor
tensor = torch.arange(16).reshape(4, 4)
print("Tensor:\n", tensor)

# Indexing
print("\nFirst row:", tensor[0])
print("Last column:", tensor[:, -1])
print("Middle 2x2 block:\n", tensor[1:3, 1:3])

# Changing elements
tensor[0, 0] = 999
print("\nAfter modifying first element:\n", tensor)

Tensor:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

First row: tensor([0, 1, 2, 3])
Last column: tensor([ 3,  7, 11, 15])
Middle 2x2 block:
 tensor([[ 5,  6],
        [ 9, 10]])

After modifying first element:
 tensor([[999,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]])


### Explanation:
- `tensor[row, column]` accesses elements  
- `:` means “all elements” along that dimension  
- Tensors are mutable — you can assign values directly to parts of them


## Reshaping Tensors

In [5]:
x = torch.arange(12)
print("Original:\n", x)

x_reshaped = x.reshape(3, 4)
print("\nReshaped to 3x4:\n", x_reshaped)

x_view = x.view(2, 6)
print("\nViewed as 2x6:\n", x_view)

x_transposed = x_reshaped.T
print("\nTransposed (swapped dimensions):\n", x_transposed)

Original:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped to 3x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Viewed as 2x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Transposed (swapped dimensions):
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


### Explanation:
- `.reshape()` creates a new tensor with a different shape (copy or view depending on memory layout).  
- `.view()` is similar but requires the data to be contiguous in memory.  
- `.T` or `.transpose()` swaps dimensions.

## Practice 1

**Task:**  
1. Create a 3×3 tensor filled with random integers between 10 and 50  
2. Convert it to a float tensor  
3. Compute its mean and standard deviation  
4. Reshape it into a 1D tensor of 9 elements

*(Hint: use `torch.randint`, `.float()`, `.mean()`, `.std()`, `.reshape()`)*

In [6]:
import torch

### Step 1: Create a 3x3 tensor with random integers between 10 and 50

In [7]:
tensor_int = torch.randint(low=10, high=51, size=(3, 3))  # high is exclusive

### Step 2: Convert it to a float tensor

In [8]:
tensor_float = tensor_int.float()

### Step 3: Compute mean and standard deviation

In [9]:
mean_value = tensor_float.mean()
std_value = tensor_float.std()

### Step 4: Reshape it into a 1D tensor of 9 elements

In [10]:
tensor_1d = tensor_float.reshape(9)

#### Print results

In [11]:
print("Original integer tensor:\n", tensor_int)
print("Float tensor:\n", tensor_float)
print("Mean:", mean_value.item())
print("Standard Deviation:", std_value.item())
print("Reshaped 1D tensor:\n", tensor_1d)

Original integer tensor:
 tensor([[21, 23, 30],
        [32, 35, 33],
        [16, 40, 44]])
Float tensor:
 tensor([[21., 23., 30.],
        [32., 35., 33.],
        [16., 40., 44.]])
Mean: 30.44444465637207
Standard Deviation: 9.070710182189941
Reshaped 1D tensor:
 tensor([21., 23., 30., 32., 35., 33., 16., 40., 44.])


## Practice 2

**Task:**  
Create two tensors of shape (2, 3) and:
- Add and multiply them element-wise  
- Perform matrix multiplication between one and the transpose of the other  
- Move one tensor to GPU (if available) and check its device

In [12]:
import torch

### Step 1: Create two tensors of shape (2, 3)

In [13]:
A = torch.randn(2, 3)  # random values from normal distribution
B = torch.randn(2, 3)

### Step 2: Element-wise addition and multiplication

In [14]:
add_result = A + B
mul_result = A * B

### Step 3: Matrix multiplication (A @ B.T)

In [15]:
matmul_result = A @ B.T  # (2x3) @ (3x2) → (2x2)

### Step 4: Move one tensor to GPU (if available)

In [16]:
if torch.cuda.is_available():
    B_gpu = B.to('cuda')
else:
    B_gpu = B  # stay on CPU if no GPU available

### Step 5: Check device

In [17]:
print("Tensor A:\n", A)
print("Tensor B:\n", B)
print("\nElement-wise addition:\n", add_result)
print("\nElement-wise multiplication:\n", mul_result)
print("\nMatrix multiplication (A @ B.T):\n", matmul_result)
print("\nB tensor device:", B_gpu.device)

Tensor A:
 tensor([[-0.0675, -0.0628, -1.8163],
        [ 0.6252,  1.4995, -1.3089]])
Tensor B:
 tensor([[-2.2711,  0.7078,  1.1520],
        [ 0.3904,  1.0262, -1.4439]])

Element-wise addition:
 tensor([[-2.3386,  0.6450, -0.6644],
        [ 1.0155,  2.5257, -2.7528]])

Element-wise multiplication:
 tensor([[ 0.1534, -0.0445, -2.0924],
        [ 0.2440,  1.5388,  1.8900]])

Matrix multiplication (A @ B.T):
 tensor([[-1.9834,  2.5318],
        [-1.8664,  3.6728]])

B tensor device: cuda:0
